/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ceejay562' at '6/14/16 12:35 AM' with Gradle 2.12
 *
 * @author ceejay562, @date 6/14/16 12:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
